apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: $APP_INSTANCE_NAME-grafana
  labels: &Labels
    k8s-app: grafana
    app.kubernetes.io/name: $APP_INSTANCE_NAME
    app.kubernetes.io/component: grafana
spec:
  serviceName: $APP_INSTANCE_NAME-grafana
  replicas: 1
  selector:
    matchLabels: *Labels
  template:
    metadata:
      labels: *Labels
    spec:
      serviceAccountName: $GRAFANA_SERVICE_ACCOUNT
      initContainers:
          - name: "init-chmod-data"
            image: $IMAGE_PROMETHEUS_INIT
            imagePullPolicy: "IfNotPresent"
            command: ["chmod", "777", "/var/lib/grafana"]
            volumeMounts:
            - name: $APP_INSTANCE_NAME-grafana-data
              mountPath: "/var/lib/grafana"
      containers:
        - name: grafana
          image: $IMAGE_GRAFANA
          imagePullPolicy: Always
          volumeMounts:
            - name: config
              mountPath: "/etc/grafana/"
            - name: dashboards
              mountPath: "/var/lib/grafana/dashboards"
            - name: datasources
              mountPath: "/etc/grafana/provisioning/datasources/"
            - name: dashboardproviders
              mountPath: "/etc/grafana/provisioning/dashboards/"
            - name: $APP_INSTANCE_NAME-grafana-data
              mountPath: "/var/lib/grafana"
          ports:
            - name: service
              containerPort: 80
              protocol: TCP
            - name: grafana
              containerPort: 3000
              protocol: TCP
          env:
            - name: GF_SECURITY_ADMIN_USER
              valueFrom:
                secretKeyRef:
                  name: $APP_INSTANCE_NAME-grafana
                  key: admin-user
            - name: GF_SECURITY_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: $APP_INSTANCE_NAME-grafana
                  key: admin-password
          livenessProbe:
            httpGet:
              path: /api/health
              port: 3000
          readinessProbe:
            httpGet:
              path: /api/health
              port: 3000
            initialDelaySeconds: 60
            timeoutSeconds: 9
            failureThreshold: 10
            periodSeconds: 10
          resources:
            limits:
              cpu: 50m
              memory: 100Mi
            requests:
              cpu: 50m
              memory: 100Mi
      volumes:
        - name: config
          configMap:
            name: $APP_INSTANCE_NAME-grafana-ini
        - name: datasources
          configMap:
            name: $APP_INSTANCE_NAME-grafana-datasources
        - name: dashboardproviders
          configMap:
            name: $APP_INSTANCE_NAME-grafana-dashboardproviders
        - name: dashboards
          configMap:
            name: $APP_INSTANCE_NAME-dashboards
  volumeClaimTemplates:
  - metadata:
      name: $APP_INSTANCE_NAME-grafana-data
    spec:
      storageClassName: $STORAGE_CLASS
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: "2Gi"
