kind: Service
apiVersion: v1
metadata:
  name: $APP_INSTANCE_NAME-prometheus
  labels:
    kubernetes.io/name: "Prometheus"
    app.kubernetes.io/name: $APP_INSTANCE_NAME
spec:
  ports:
    - name: http
      port: 9090
      protocol: TCP
      targetPort: 9090
  sessionAffinity: ClientIP
  selector:
    k8s-app: prometheus
