application_api_version: v1beta1
properties:
  APP_INSTANCE_NAME:
    type: string
    x-google-marketplace:
      type: NAME
  NAMESPACE:
    type: string
    x-google-marketplace:
      type: NAMESPACE
  IMAGE_WORDPRESS:
    type: string
    default: $REGISTRY:$TAG
    x-google-marketplace:
      type: IMAGE
  IMAGE_MYSQL:
    type: string
    default: $REGISTRY/mysql:$TAG
    x-google-marketplace:
      type: IMAGE
  ROOT_DB_PASSWORD:
    type: string
    x-google-marketplace:
      type: GENERATED_PASSWORD
      generatedPassword:
        length: 12
  WORDPRESS_DB_PASSWORD:
    type: string
    x-google-marketplace:
      type: GENERATED_PASSWORD
      generatedPassword:
        length: 12
  WPADMINISTRATOR_IP_ADDRESS:
    type: string
    default: 127.0.0.1
required:
- APP_INSTANCE_NAME
- NAMESPACE
- IMAGE_WORDPRESS
- IMAGE_MYSQL
- ROOT_DB_PASSWORD
- WORDPRESS_DB_PASSWORD
- WPADMINISTRATOR_IP_ADDRESS
