application_api_version: v1beta1
properties:
  name:
    type: string
    x-google-marketplace:
      type: NAME
  namespace:
    type: string
    x-google-marketplace:
      type: NAMESPACE
  wordpressImage:
    type: string
    default: $REGISTRY:$TAG
    x-google-marketplace:
      type: IMAGE
  db.image:
    type: string
    default: $REGISTRY/mysql:$TAG
    x-google-marketplace:
      type: IMAGE
  db.rootPassword:
    type: string
    x-google-marketplace:
      type: GENERATED_PASSWORD
      generatedPassword:
        length: 12
  db.password:
    type: string
    x-google-marketplace:
      type: GENERATED_PASSWORD
      generatedPassword:
        length: 12
  # An e-mail address for WordPress site.
  admin.email:
    type: string
    title: WordPress admin e-mail address
    description: The e-mail address for administrator account of WordPress.
    default: noreply@example.com
    # https://www.w3.org/TR/html52/sec-forms.html#email-state-typeemail
    pattern: ^[a-zA-Z0-9.!#$%&'*+\/=?^_`{|}~-]+@[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?(?:\.[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?)*$
  # A password for WordPress site.
  admin.password:
    type: string
    x-google-marketplace:
      type: GENERATED_PASSWORD
      generatedPassword:
        length: 20
required:
- name
- namespace
- wordpressImage
- db.image
- db.rootPassword
- db.wordpressPassword
- admin.email
- admin.password
