x-google-marketplace:
  applicationApiVersion: v1beta1
  # IMPORTANT: These IDs must match your listing ID in Marketplace.
  schemaVersion: v2
  partnerId: click-to-deploy-containers
  solutionId: aditum
  # The release version is required in the schema and MUST match the
  # release tag on the the deployer. Must be in x.x.x format!
  publishedVersion: 1.3.2
  publishedVersionMetadata:
    releaseNote: >-
      First release of Custom Governance.
    # releaseTypes list is optional.
    # "Security" should only be used if this is an important update to patch
    # an existing vulnerability, as such updates will display more prominently for users.
    releaseTypes:
    - Feature
    # If "recommended" is "true", users using older releases are encouraged
    # to update as soon as possible. This is useful if, for example, this release
    # fixes a critical issue.
    recommended: true

  # This MUST be specified to indicate that the deployer supports managed updates.
  # Note that this could be left out or kalmSupported set to false, in
  # which case the deployer uses schema v2 but does not support updates.
  managedUpdates:
    kalmSupported: true
  ## Image Values
  images:
    '':  # Primary image has no name.
      properties:
        cg.image.repo:
          type: REPO_WITH_REGISTRY
        cg.image.tag:
          type: TAG
  ## Cluster Constraints
  clusterConstraints:
    assistedClusterCreation:
      type: STRICT
      creationGuidance: "The cloud-platform scope must be enabled on the cluster. In addition we recommened a cluster with minimum 4vCPUs and 15GB of memory."
      gke:
        nodePool:
        - numNodes: 3
          machineType: n1-standard-4
    gcp:
      nodes:
        requiredOauthScopes:
        - https://www.googleapis.com/auth/cloud-platform
        - https://www.googleapis.com/auth/devstorage.read_only


properties:
  name:
    type: string
    x-google-marketplace:
      type: NAME
  namespace:
    type: string
    x-google-marketplace:
      type: NAMESPACE
  oAuth.clientID:
    type: string
    title: OAuth Client ID
    description: Please refer to the Installation Guide to create your OAuth Client ID
    x-google-marketplace:
      type: STRING
      string:
        generatedProperties:
          base64Encoded: oAuth.clientIDEncoded
  oAuth.clientSecret:
    type: string
    title: OAuth Client Secret
    description: Please refer to the Installation Guide to create your OAuth Client Secret
    x-google-marketplace:
      type: STRING
      string:
        generatedProperties:
          base64Encoded: oAuth.clientSecretEncoded
  deployment.staticIP:
    type: string
    title: Name of Global Static IP Address, e.g. static-ip-name
    description: Please refer to the Installation Guide to create your Static IP Address. This is the NAME of the static address, NOT the IP address that is assigned
  certificate.hostname:
    type: string
    title: Full Domain Name to serve Custom Governance, e.g. cg.example.com
    description: The full domain name that will point to the static IP address. Read the Installation Guide for more information
  controller.serviceAccount:
    type: string
    title: Kubernetes Service Account
    description: A new service account will be created using cluster edit role within the namespace to allow access to the Kubernetes Secrets
    x-google-marketplace:
      type: SERVICE_ACCOUNT
      serviceAccount:
        description: Reads the OAuth Client Secret and creates app resources post-deployment.
        roles:
        - type: Role
          rulesType: PREDEFINED
          rulesFromRoleName: edit
  setupAttributes.initialEmail:
    type: string
    title: Initial End User Email e.g. user@example.com
    description:  The email address of the user that will be deploying/setting up Custom Governance
required:
- name
- namespace
- oAuth.clientSecret
- oAuth.clientID
- certificate.hostname
- deployment.staticIP
- setupAttributes.initialEmail
