application_api_version: v1beta1
properties:
  APP_INSTANCE_NAME:
    type: string
    x-google-marketplace:
      type: NAME
  NAMESPACE:
    type: string
    x-google-marketplace:
      type: NAMESPACE
  PROMETHEUS_REPLICAS:
    type: integer
    title: Prometheus replicas
    description: The number of replicas for Prometheus StatefulSet
    default: 2
    minimum: 1
  GRAFANA_GENERATED_PASSWORD:
    type: string
    x-google-marketplace:
      type: GENERATED_PASSWORD
      generatedPassword:
        length: 12
  IMAGE_PROMETHEUS:
    type: string
    default: $REGISTRY:$TAG
    x-google-marketplace:
      type: IMAGE
  IMAGE_ALERTMANAGER:
    type: string
    default: $REGISTRY/alertmanager:$TAG
    x-google-marketplace:
      type: IMAGE
  IMAGE_KUBE_STATE_METRICS:
    type: string
    default: $REGISTRY/kubestatemetrics:$TAG
    x-google-marketplace:
      type: IMAGE
  IMAGE_NODE_EXPORTER:
    type: string
    default: $REGISTRY/nodeexporter:$TAG
    x-google-marketplace:
      type: IMAGE
  IMAGE_GRAFANA:
    type: string
    default: $REGISTRY/grafana:$TAG
    x-google-marketplace:
      type: IMAGE
  IMAGE_PROMETHEUS_INIT:
    type: string
    default: $REGISTRY/debian9:$TAG
    x-google-marketplace:
      type: IMAGE
  PROMETHEUS_SERVICE_ACCOUNT:
    type: string
    title: Prometheus Service Account
    description: Service account to assign to main Prometheus StatefulSet
    x-google-marketplace:
      type: SERVICE_ACCOUNT
      serviceAccount:
        roles:
        - type: ClusterRole
          rulesType: PREDEFINED
          rulesFromRoleName: cluster-admin
  KUBE_STATE_METRICS_SERVICE_ACCOUNT:
    type: string
    title: Kube State Metrics Service Account
    description: Service account to assign to main Kube State Metrics Deployment
    x-google-marketplace:
      type: SERVICE_ACCOUNT
      serviceAccount:
        roles:
        - type: ClusterRole
          rulesType: CUSTOM
          rules:
          - apiGroups: [""]
            resources:
            - configmaps
            - secrets
            - nodes
            - pods
            - services
            - resourcequotas
            - replicationcontrollers
            - limitranges
            - persistentvolumeclaims
            - persistentvolumes
            - namespaces
            - endpoints
            verbs: ["list", "watch", "get"]
          - apiGroups: ["extensions"]
            resources:
            - daemonsets
            - deployments
            - replicasets
            verbs: ["list", "watch", "get", "update"]
          - apiGroups: ["apps"]
            resources:
            - statefulsets
            verbs: ["list", "watch"]
          - apiGroups: ["batch"]
            resources:
            - cronjobs
            - jobs
            verbs: ["list", "watch"]
          - apiGroups: ["autoscaling"]
            resources:
            - horizontalpodautoscalers
            verbs: ["list", "watch"]
  ALERTMANAGER_SERVICE_ACCOUNT:
    type: string
    title: Alertmanager Service Account
    description: Service account to assign to Alertmanager StatefulSet
    x-google-marketplace:
      type: SERVICE_ACCOUNT
      serviceAccount:
        roles:
        - type: ClusterRole
          rulesType: PREDEFINED
          rulesFromRoleName: cluster-admin
  GRAFANA_SERVICE_ACCOUNT:
    type: string
    title: Grafana Service Account
    description: Service account to assign to Grafana StatefulSet
    x-google-marketplace:
      type: SERVICE_ACCOUNT
      serviceAccount:
        roles:
        - type: ClusterRole
          rulesType: PREDEFINED
          rulesFromRoleName: cluster-admin
  NODE_EXPORTER_SERVICE_ACCOUNT:
    type: string
    title: Node Exporter Service Account
    description: Service account to assign to Node Exporter DaemonSet
    x-google-marketplace:
      type: SERVICE_ACCOUNT
      serviceAccount:
        roles:
        - type: ClusterRole
          rulesType: PREDEFINED
          rulesFromRoleName: cluster-admin
  STORAGE_CLASS:
    type: string
    title: StorageClass
    description: You can choose an existing StorageClass or create a new one.
    x-google-marketplace:
      type: STORAGE_CLASS
      storageClass:
        type: SSD

required:
- APP_INSTANCE_NAME
- NAMESPACE
- STORAGE_CLASS
- PROMETHEUS_REPLICAS
- GRAFANA_GENERATED_PASSWORD
- IMAGE_ALERTMANAGER
- IMAGE_KUBE_STATE_METRICS
- IMAGE_NODE_EXPORTER
- IMAGE_PROMETHEUS
- IMAGE_GRAFANA
- IMAGE_PROMETHEUS_INIT
- PROMETHEUS_SERVICE_ACCOUNT
- KUBE_STATE_METRICS_SERVICE_ACCOUNT
- ALERTMANAGER_SERVICE_ACCOUNT
- GRAFANA_SERVICE_ACCOUNT
- NODE_EXPORTER_SERVICE_ACCOUNT
