apiVersion: v1
appVersion: 3.5.0
description: etcd is a distributed reliable key-value store which is written in GO and uses the Raft consensus algorithm to manage a highly-available replicated log.
name: etcd
version: 3.5.0
