matrix:
  include:
  - language: python
    python: 2.7
    install: pip install jinja2 pyyaml
    env: TARGET=python-test
  - language: ruby
    install: gem install foodcritic
    env: TARGET=vm-lint
  - language: ruby
    rvm:
    - 2.5
    install: gem install knife-solo
    env: TARGET=vm-generate-triggers
  - language: generic
    dist: xenial
    before_install:
    - wget https://packages.chef.io/files/stable/chefdk/4.2.0/ubuntu/16.04/chefdk_4.2.0-1_amd64.deb
    - sudo dpkg -i chefdk_4.2.0-1_amd64.deb
    env: TARGET=vm-generate-triggers

script: make "${TARGET}"
