# Copyright 2020 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

description: Trigger for K8s airflow-operator
filename: cloudbuild-k8s.yaml
github:
  installationId: '261964'
  name: click-to-deploy
  owner: GoogleCloudPlatform
  pullRequest:
    branch: .*
    commentControl: COMMENTS_ENABLED
id: e9845336-fe28-44de-b53b-26e9812a8c4a
includedFiles:
- cloudbuild-k8s.yaml
- k8s.Dockerfile
- k8s/airflow-operator/**
- k8s/*
name: Trigger-for-K8s-airflow-operator
substitutions:
  _SOLUTION_NAME: airflow-operator
