apiVersion: apps/v1beta2
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-cassandra
  labels: &CassandraDeploymentLabels
    app.kubernetes.io/name: "{{ .Release.Name }}"
    app.kubernetes.io/component: cassandra-server
spec:
  selector:
    matchLabels: *CassandraDeploymentLabels
  serviceName: {{ .Release.Name }}-cassandra-svc
  replicas: {{ .Values.cassandra.replicas }}
  updateStrategy:
      type: OnDelete
  template:
    metadata:
      labels: *CassandraDeploymentLabels
    spec:
      terminationGracePeriodSeconds: 180
      containers:
      - name: cassandra
        image: {{ .Values.cassandra.image }}
        imagePullPolicy: Always
        env:
        - name: CASSANDRA_CGROUP_MEMORY_LIMIT
          value: 'true'
        - name: CASSANDRA_CLUSTER_NAME
          value: {{ .Release.Name }}-cassandra-svc
        - name: CASSANDRA_PROMETHEUS_ENABLED
          value: 'true'
        - name: CASSANDRA_SEEDS
          value: {{ .Release.Name }}-cassandra-0.{{ .Release.Name }}-cassandra-svc.{{ .Release.Namespace }}.svc.cluster.local, {{ .Release.Name }}-cassandra-1.{{ .Release.Name }}-cassandra-svc.{{ .Release.Namespace }}.svc.cluster.local, {{ .Release.Name }}-cassandra-2.{{ .Release.Name }}-cassandra-svc.{{ .Release.Namespace }}.svc.cluster.local
        ports:
        - name: pure-intra
          containerPort: 7000
        - name: tls-intra
          containerPort: 7001
        - name: jmx
          containerPort: 7199
        - name: cql
          containerPort: 9042
        - name: thrift
          containerPort: 9160
        - name: prometheus
          containerPort: 9404
        resources:
          requests:
           cpu: 500m
           memory: 4Gi
          limits:
           cpu: 500m
           memory: 4Gi
        volumeMounts:
        - name: {{ .Release.Name }}-cassandra-pvc
          mountPath: /var/lib/cassandra
        livenessProbe:
          exec:
            command: [ "/bin/sh", "-c", "nodetool status" ]
          initialDelaySeconds: 90
          periodSeconds: 30
        readinessProbe:
          exec:
            command: [ "/bin/sh", "-c", "nodetool status | grep -E \"^UN\\s+${POD_IP}\"" ]
          initialDelaySeconds: 90
          periodSeconds: 30
        lifecycle:
          preStop:
            exec:
              command:
              - "/bin/sh"
              - "-c"
              - "nodetool drain"
      {{ if .Values.metrics.enabled }}
      - name: prometheus-to-sd
        image: {{ .Values.metrics.image }}
        ports:
        - name: profiler
          containerPort: 6060
        command:
        - /monitor
        - --stackdriver-prefix=custom.googleapis.com
        - --source=cassandra:http://localhost:9404/metrics
        - --pod-id=$(POD_NAME)
        - --namespace-id=$(POD_NAMESPACE)
        - --monitored-resource-types=k8s
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
      {{ end }}
  volumeClaimTemplates:
  - metadata:
      name: {{ .Release.Name }}-cassandra-pvc
      labels: *CassandraDeploymentLabels
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: standard
      resources:
        requests:
          storage: 5Gi
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-cassandra-svc
  labels:
    app.kubernetes.io/name: "{{ .Release.Name }}"
    app.kubernetes.io/component: cassandra-server
spec:
  ports:
  - name: cql
    port: 9042
  - name: thrift
    port: 9160
  selector:
    app.kubernetes.io/name: "{{ .Release.Name }}"
    app.kubernetes.io/component: cassandra-server
  type: ClusterIP
# While bootstraping Cassandra, we need to provide a list of IPs or hostnames
# to connect. Setting clusterIP to None enables connection between Cassandra
# nodes directly.
  clusterIP: None
