application_api_version: v1beta1
properties:
  name:
    type: string
    x-google-marketplace:
      type: NAME
  namespace:
    type: string
    x-google-marketplace:
      type: NAMESPACE
  nginx.image:
    type: string
    default: $REGISTRY:$TAG
    x-google-marketplace:
      type: IMAGE
  nginx.initImage:
    type: string
    default: $REGISTRY/debian9:$TAG
    x-google-marketplace:
      type: IMAGE
  nginx.replicas:
    type: integer
    title: Replicas
    description: The number of Pods run within NGINX solution
    default: 3
    minimum: 1
  certificate:
    type: string
    x-google-marketplace:
      type: TLS_CERTIFICATE
      tlsCertificate:
        generatedProperties:
          base64EncodedPrivateKey: tls.base64EncodedPrivateKey
          base64EncodedCertificate: tls.base64EncodedCertificate
required:
- name
- namespace
- nginx.image
- nginx.initImage
- nginx.replicas
