apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: "$APP_INSTANCE_NAME"
  annotations:
    kubernetes-engine.cloud.google.com/icon: >-
      data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAIIAAACCCAMAAAC93eDPAAAABGdBTUEAALGPC/xhBQAAAAFzUkdCAK7OHOkAAAMAUExURQAAAACbAACbAACbAACbAACbAACbAACbAACbAACbAACbAACbAACYAACbAACbAACbAACbAACbAACbAACbAACbAACbAACWAACbAACZAACbAACaAACbAACbAACbAACaAACbAACbAACbAACbAACaAACaAACbAACZAACbAACbAACbAACbAACbAACaAACaAACbAACaAACbAACZAACbAACaAACaAACbAACaAACbAACbAACaAACaAACaAACaAACaAACbAACbAACaAACbAACbAACZAACbAACaAACbAACbAACYAACbAACaAACbAACZAACbAACbAACbAACaAACbAACbAACbAACbAACbAACaAACbAACbAACZAACaAACaAACbAACaAACaAACaAACbAACaAACbAACbAACbAACZAACaAACbAACaAACaAACbAACaAACaAACaAACaAACbAACbAACbAACaAACbAACbAACbAACaAACbAACaAACZAACaAACaAACbAACaAACaAACbAACbAACbAACbAACbAACaAACaAACaAACbAACbAACbAACaAACbAACaAACaAACbAACaAACaAACbAACaAACbAACbAACbAACbAACbAACbAACXAACZAACaAACbAACbAACbAACaAACbAACbAACbAACaAACbAACbAACbAACbAACbAACaAACbAACZAACaAACbAACbAACbAACbAACbAACaAACaAACaAACbAACaAACbAACbAACZAACaAACVAACbAACbAACaAACbAACbAACaAACaAACbAACbAACbAACbAACbAACbAACbAACaAACaAACbAACbAACaAACbAACbAACbAACbAACbAACaAACbAACZAACaAACZAACbAACbAACbAACbAACaAACZAACaAACbAACaAACbAACbAACbAACaAACaAACbAACbAACbAACaAACaAACbAACaAACbAACbAACaAACaAACaAACaAACaAACaAACaAACaAACbAACaAACaAACbAACbAACbAACaAACbANJeAvUAAAD/dFJOUwCoSvxPpP77+swo6wOmkD/1+HXx/YIB9wbOCL2j8Az5uYj0Hw3hDoHDwJ3qBxqgNewC8hc/9guPkUYkMDEz7Y0VyJwQsyOUyQSWOPMLgOJ8Qre/CO/dPM3LFCAv4y4ULOhQtqfeGT21DyLGWh5YG1MEylG6vIkSYUcJNE3PKnFt0Ce0ohYTSNjS5gqlSy1wTmKMIXdOrtrU2wIIKJOq7mCvrT4r54ff0eRtbBNEBXrpwlJcaKyGX8WbBUMCXZ5KeFxWUtZgmERDq5I3MtV5HeVl07g2GGkWYRKZJHRoRRUcsoyLjp9djlZkg4p7wZZze3SCETlbV3MlrGc6NdcuTyzHxewAAAU3SURBVHja7ZdXWFRHFIAPortLgprNbnYXgQWWtlQRaYYaBETpBFGjQqxgQSzRWGOJUWPsUROTGGONLZZ0Y3rvvffee+/XOzO3zC3Al5e8eP4Hdhpz/52dOXMuAIIgCIIgCIIgCIIgCIIgCIIgCIL8X+Q+Hh6x5GGPtrF3kG3VCqV2siYkiCPknoFKV3JNmmOjVyx4ZzeEF8ZoJnENSMj0vdhIy55LRtlD++oenVLsCB88AXKHCyKOA9v4via/2DZsmlzNqxY0RCxWRnZzCIL7frFws1tsv1jzhBWxZPDKl0h5jDhOCJmv6e8fYBGEwMFwK5s1bQzfOYT8g/sxqeZJFHTEKt/nNlItFgt3kkKqi5tk7VVscIC4wq5UWlyYrzGgbddDgzTryqf43+EsscXaTarNDdcrCO/LP0UvUuspFnrQpwWrcyxvkcaOjxYVwlh5WJ7S/+o4C21KB2XW0GkdKMSNNRgI1u+7UkjOsUhjk84Qq1PcrBKUK/W/ewXrt4SpCkJipbnC7RGkNyH+HEp8gJVU9//ZhcIrmfK8ZxKFa6JsrDZ8JO0eESYZlkRzCrZngs0UUuh+vXCI3Heojo6uO9Spwjt7BI0CZH0oOQwaTQwulQzGTgWm4HCSvw0PmCkcoYMLT6p7lZ4P5xFXJwpLF6rzMgXI2ig5nLcWLkuVDOouAEnhm6/px9AnjQq7x5Oeq6/lNusBOtfR2o4VXr+Bzrd1r11VAO9HVvbcyRMTnawUSQyYwrd96YMEf7ReIbiM7pkr+SMbl3MsISHBH0/C2UF/fb2/RqfgmU0f4fhsvY1TAG8vySFJWo9Zk0BROBva2MELi9MpZKTRfZyiiSnT+1DILzH9fJGbdAobfKQSWAWbNQoQk2Plj9VFpcArBH9HzaxV5RqFrJ10o77WdZznFDJG0UnHtUJ3rQLEXReoGoSeCxoF8H7MAsUnGoVf6NGKpIHIk7+5u4Z/xUjyT/vx4+1/aRRKB7FdJ66yXgHiyqwGA0UB3qtnsXcipxBMJxbW0VjzRVqgBsvfvwFkC06n0INXaGVxt3oXmCjAJilqC+n3gkEB5m9l57aUW4U2dRVq03UR0vmr2Ykoj6dr7aM31n9cBYAHC2hl+4+qQiU9XbYNYu/n+iA9ub+Zws8Oqhd1wkwhptO9INLvLRqKnXu37VJORG2BfCJ66y4rd5tJXHD9tI927pwDJgqdnwjK6kdozbcjQ1Eof0OOC56v9tgZLK5syTIq9Jzkp30hS8FEwZstxwXpc9YmgwK8HMm25A8VSnQcGStHx/LdhweIHJ5CW9IyTO6IFrZ9L38UTBS8n3YWHWUFGP00i+2B6h0RL+juiD/oTGXlJgoVNLhkvg0mCpUfyHdEM3dHRBsUYM1RNSdgCtGrtDfl1BvpdbLI7LJmGUB2solC5Zf8TdlkuClVBddit04BbrHy+ULV72QRLfdBhwrLisCooOQLM1i+0KTPF1QF6KNkO7LCnHpj1jRjQocKLzSDiYIhayrSZU2cAhSVSHNVNEotM316A/vdoFd4Qk7T1oCJgknuuFzJHcmNLhzkL5xFS6RtM0JqmLddr1CivDBE0ZRPLLSzr2lfxyfRc8nsz72pZNAhphn0MnKItO8YtUPpBpypNDQmaQ0K7lK6FojHN2IHSYqKyR6xZc/jZ3qWbN0tq5X3iHzT94jmFnv18/20F29GpM99x3r15eZElPZtqjBZ3TpVBY5suiZFUfut+2patTMteMh2LK+rtykEQRAEQRAEQRAEQRAEQRAEQRDk9OAURpCcjQcYD6YAAAAASUVORK5CYII=
    marketplace.cloud.google.com/deploy-info: '{partner_id: "click-to-deploy-containers", product_id: "nginx", partner_name: "Google Click to Deploy"}'
  labels:
    app.kubernetes.io/name: "$APP_INSTANCE_NAME"
spec:
  descriptor:
    type: NGINX
    version: '1.15'
    description: |-
      NGINX is open-source software for web serving, reverse proxying,
      caching, load balancing, and media streaming.

      NGINX can also function as a proxy server for email (IMAP, POP3, and SMTP)
      and a reverse proxy and load balancer for HTTP, TCP, and UDP servers.

      If you would like to learn more about NGINX, please,
      visit [NGINX website](https://www.nginx.com/).

      # Support

      This image is built by Google. It is your responsibility to keep
      container images you run or store in your own repositories
      up to date with security patches.

      Community support for NGINX is available on
      [Stack Overflow](http://stackoverflow.com/questions/tagged/nginx/).

      Please report issues with this NGINX container image via
      the [GitHub Issue Tracker](https://github.com/GoogleCloudPlatform/nginx-docker/issues).
    maintainers:
    - name: Google Click to Deploy
      url: https://cloud.google.com/solutions/#click-to-deploy
    links:
    - description: 'User Guide: Google Click to Deploy NGINX'
      url: https://github.com/GoogleCloudPlatform/nginx-docker/blob/master/1/README.md
    - description: 'NGINX: Getting Started'
      url: https://www.nginx.com/resources/wiki/start/
    notes: |-
      # Configuring the web content of NGINX server
      
      Follow this instructions to upload web content to your Web Server:

      1. Navigate to a folder where directory containing your website is located
         (e.g. assuming that your web content is stored in `html` directory)
      1. Run the following command to copy the content of `html` directory to the Persistent Volume:
         ```
         kubectl cp html $APP_INSTANCE_NAME-nginx-0:/usr/share/nginx -n $NAMESPACE
         ```
      1. Set permissions so NGINX server has access to the newly uploaded `html` directory:
         ```
         kubectl exec $APP_INSTANCE_NAME-nginx-0 -n $NAMESPACE -- chmod -R a+r /usr/share/nginx/html
         ```
      # Configuring SSL certificate for NGINX server

      This version of NGINX application uses pre-generated certificate which is self-signed and is meant to be
      only a temporary solution just to exemplify SSL/TLS configuration.

      Generate a new self-signed certificate for your NGINX server using `openssl` command
      or use a signed certifcate that you already own.

      For example, if you would like to generate self-signed certifcate and private key
      you could run the following command:
      ```
      openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout https1.key -out https1.cert
      ```

      Configure your own certificate using the following command:
      ```
      export CERT_FILE=https1.cert
      export KEY_FILE=https1.key
      export APP_INSTANCE_NAME=<name of your NGINX instance, e.g. nginx-1>
      export NAMESPACE=<name of your Kurbernetes namespace, e.g. default>

      # using --dry-run option because we update existing secret resource
      # if we used kubectl create... for existing secret we would get an error
      kubectl --namespace $NAMESPACE create secret generic $APP_INSTANCE_NAME-nginx-secret \
        --from-file=$CERT_FILE --from-file=$KEY_FILE \
        --dry-run -o yaml | kubectl apply -f -
      ```
      where .cert is a file containing SSL certificate and .key file contains private part of it.


      Run these commands to restart all Pods without causing a downtime
      ```
      PODS=$(kubectl get pods --namespace $NAMESPACE -l app.kubernetes.io/name=$APP_INSTANCE_NAME | awk 'FNR>1 {print $1}')

      TIMEOUT=60

      for i in ${PODS[@]}; do
        echo "Deleting Pod: $i..."
        kubectl delete pod $i --namespace $NAMESPACE
        echo "Sleeping for $TIMEOUT seconds..."
        sleep $TIMEOUT
      done
      ```
  info:
  - name: Nginx External IP
    type: Reference
    valueFrom:
      serviceRef:
        name: $APP_INSTANCE_NAME-nginx-svc
  - name: Application Namespace
    value: $NAMESPACE
  - name: Nginx Configuration
    value: nginx-config.conf
  - name: Nginx Cert
    type: Reference
    valueFrom:
      secretKeyRef:
        key: https1.cert
        name: $APP_INSTANCE_NAME-nginx-secret
  - name: Nginx Key
    type: Reference
    valueFrom:
      secretKeyRef:
        key: https1.key
        name: $APP_INSTANCE_NAME-nginx-secret
  selector:
    matchLabels:
      app.kubernetes.io/name: "$APP_INSTANCE_NAME"
  componentKinds:
  - group: v1
    kind: ConfigMap
  - group: v1
    kind: PersistentVolumeClaim
  - group: apps/v1beta2
    kind: StatefulSet
  - group: v1
    kind: Secret
  - group: v1
    kind: Service
