wordpressImage: null

db:
  image: null
  rootPassword: null
  wordpressUser: wordpress
  wordpressPassword: null

  # The image and credentials for mysqld_exporter component.
  exporter:
    image: null
    user: mysqld-exporter
    password: null

apache:
  exporter:
    image: null

admin:
  username: admin
  email: admin@example.com
  password: null

metrics:
  image: null
  enabled: false
