initImage: null

elasticsearch:
  image:
    repo: null
    tag: null
  replicas: null

fluentd:
  serviceAccount: null

kibana:
  image: null

fluentd:
  image: null

metrics:
  image: null
  enabled: false
