---
{{- $secret := (lookup "v1" "Secret" .Release.Namespace (printf "%s-config-envs" .Release.Name)) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-config-envs
  labels:
    {{ include "keycloak.labels" . | indent 4 }}
data:
  {{- if $secret }}
  KC_DB_PASSWORD: {{ $secret.data.KC_DB_PASSWORD }}
  {{- else }}
  KC_DB_PASSWORD: {{ randAlphaNum 32 | b64enc | quote }}
  {{- end }}
  KEYCLOAK_ADMIN_PASSWORD: {{ .Values.keycloak.admin.password | toString | b64enc | quote }}


