apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-memcached
  labels: &MemcachedDeploymentLabels
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/component: memcached-server
spec:
  selector:
    matchLabels: *MemcachedDeploymentLabels
  updateStrategy:
    type: RollingUpdate
  serviceName: {{ .Release.Name }}-memcached-svc
  replicas: {{ .Values.memcached.replicas }}
  template:
    metadata:
      labels: *MemcachedDeploymentLabels
    spec:
      terminationGracePeriodSeconds: 180
      containers:
      - name: memcached
        image: "{{ .Values.memcached.image.repo }}:{{ .Values.memcached.image.tag }}"
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        env:
        - name: MEMCACHED_PROMETHEUS_ENABLED
          value: "true"
        ports:
        - name: prometheus
          containerPort: 9150
          protocol: TCP
        - name: memcached
          containerPort: 11211
          protocol: TCP
        livenessProbe:
          tcpSocket:
            port: memcached
          initialDelaySeconds: 10
          timeoutSeconds: 5
        readinessProbe:
          tcpSocket:
            port: memcached
          initialDelaySeconds: 5
          timeoutSeconds: 2
      {{ if .Values.metrics.exporter.enabled }}
      - name: prometheus-to-sd
        image: {{ .Values.metrics.image }}
        ports:
        - name: profiler
          containerPort: 6060
        command:
        - /monitor
        - --stackdriver-prefix=custom.googleapis.com
        - --source=$(POD_NAME):http://localhost:9150/metrics
        - --pod-id=$(POD_NAME)
        - --namespace-id=$(POD_NAMESPACE)
        - --scrape-interval=5s
        - --export-interval=30s
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
      {{ end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-memcached-prometheus-svc
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/component: memcached-server
spec:
  clusterIP: None
  ports:
  - name: prometheus-port
    port: 9150
    protocol: TCP
  selector:
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/component: memcached-server
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-memcached-svc
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/component: memcached-server
spec:
  clusterIP: None
  ports:
  - name: memcached-port
    port: 11211
    protocol: TCP
  selector:
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/component: memcached-server
  type: ClusterIP # LoadBalancer
