properties:
  APP_INSTANCE_NAME:
    type: string
    x-google-marketplace:
      type: NAME
  NAMESPACE:
    type: string
    x-google-marketplace:
      type: NAMESPACE
  IMAGE_MEMCACHED:
    type: string
    default: $REGISTRY:$TAG
    x-google-marketplace:
      type: IMAGE
  REPLICAS:
    title: Replicas
    description: The number of pods in the solution
    type: integer
    default: 3
    minimum: 1
    maximum: 30
required:
- APP_INSTANCE_NAME
- NAMESPACE
- IMAGE_MEMCACHED
- REPLICAS
