application_api_version: v1beta1
properties:
  name:
    type: string
    x-google-marketplace:
      type: NAME
  namespace:
    type: string
    x-google-marketplace:
      type: NAMESPACE
  memcached.image:
    type: string
    default: $REGISTRY:$TAG
    x-google-marketplace:
      type: IMAGE
  memcached.replicas}}:
    type: integer
    title: Replicas
    description: The number of Pods in the solution
    default: 3
    minimum: 1
    maximum: 11
required:
- name
- namespace
- memcached.image
- memcached.replicas}}
