---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ template "prometheus.prometheusName" . }}-prometheus
  labels: &Labels
    k8s-app: prometheus
    app.kubernetes.io/name: "{{ .Release.Name }}"
    app.kubernetes.io/component: prometheus
spec:
  serviceName: "{{ .Release.Name }}-prometheus"
  replicas: {{ .Values.prometheus.replicas }}
  podManagementPolicy: "Parallel"
  updateStrategy:
    type: "RollingUpdate"
  selector:
    matchLabels: *Labels
  template:
    metadata:
      labels: *Labels
    spec:
      serviceAccountName: "{{ .Values.prometheus.serviceAccountName }}"
      initContainers:
      - name: "init-chown-data"
        image: busybox:1.35
        imagePullPolicy: Always
        command: ["chown", "-R", "65534:65534", "/data"]
        volumeMounts:
        - name: {{ .Release.Name }}-prometheus-data
          mountPath: /data
          subPath: ""
      containers:
        - name: prometheus-server
          image: "{{ .Values.prometheus.image.repo }}:{{ .Values.prometheus.image.tag }}"
          imagePullPolicy: "IfNotPresent"
          # command: ["tail", "-f", "/dev/null"]
          args:
            - --config.file=/etc/config/prometheus.yaml
            - --storage.tsdb.path=/data
            - --web.console.libraries=/etc/prometheus/console_libraries
            - --web.console.templates=/etc/prometheus/consoles
            - --web.enable-lifecycle
          ports:
            - containerPort: 9090
          readinessProbe:
            httpGet:
              path: /-/ready
              port: 9090
            initialDelaySeconds: 30
            timeoutSeconds: 30
          livenessProbe:
            httpGet:
              path: /-/healthy
              port: 9090
            initialDelaySeconds: 30
            timeoutSeconds: 30
          # based on 10 running nodes with 30 pods each
          resources:
            requests:
              cpu: 200m
              memory: 1000Mi
          volumeMounts:
            - name: config-volume
              mountPath: /etc/config
            - name: {{ template "prometheus.prometheusName" . }}-prometheus-data
              mountPath: /data
              subPath: ""
      terminationGracePeriodSeconds: 300
      volumes:
        - name: config-volume
          configMap:
            name: {{ .Release.Name }}-prometheus-config
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: k8s-app
                operator: In
                values:
                - prometheus
            topologyKey: "kubernetes.io/hostname"
  volumeClaimTemplates:
  - metadata:
      name: {{ template "prometheus.prometheusName" . }}-prometheus-data
      labels: *Labels
    spec:
      storageClassName: "{{ .Values.prometheus.storageClass }}"
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: "16Gi"
