x-google-marketplace:
  schemaVersion: v2

  applicationApiVersion: v1beta1

  publishedVersion: "$TAG"
  publishedVersionMetadata:
    releaseNote: >-
      A regular update.
    releaseTypes:
      - Feature
    recommended: false

  managedUpdates:
    kalmSupported: false

  images:
    '':
      properties:
        postgresql.image.repo:
          type: REPO_WITH_REGISTRY
        postgresql.image.tag:
          type: TAG
    exporter:
      properties:
        exporter.image:
          type: FULL
    prometheus-to-sd:
      properties:
        postgresql.image:
          type: FULL

properties:
  name:
    type: string
    x-google-marketplace:
      type: NAME
  namespace:
    type: string
    x-google-marketplace:
      type: NAMESPACE
  postgresql.volumeSize:
    type: integer
    title: Volume
    description: The size of Volume (Gi) in the solution
    default: 24
  postgresql.serviceAccount:
    type: string
    title: PostgreSQL service account
    description: >-
      Service account to assign to PostgreSQL StatefulSet (with default permissions)
    x-google-marketplace:
      type: SERVICE_ACCOUNT
  postgresql.exposePublicService:
    type: boolean
    title: Enable public IP access
    description: Set the PostgreSQL Service type to LoadBalancer
    default: false
  db.password:
    type: string
    x-google-marketplace:
      type: GENERATED_PASSWORD
      generatedPassword:
        length: 12
  metrics.enabled:
    type: boolean
    title: Enable Stackdriver Metrics Exporter
    description: Your GCP project should have Stackdriver enabled. For non-GCP clusters, export of metrics to Stackdriver is not supported yet
    default: false
  certificate:
    type: string
    x-google-marketplace:
      type: TLS_CERTIFICATE
      tlsCertificate:
        generatedProperties:
          base64EncodedPrivateKey: tls.base64EncodedPrivateKey
          base64EncodedCertificate: tls.base64EncodedCertificate

required:
- name
- namespace
- postgresql.volumeSize
- postgresql.serviceAccount
- postgresql.exposePublicService
- db.password
- metrics.enabled
- certificate
