---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-superset-secret
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/component: apache-superset
type: Opaque
data:
  superset-password: {{ .Values.superset.password | b64enc | quote }}
{{ if .Values.enablePublicServiceAndIngress }}
{{ end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{.Release.Name}}-postgresql-secret
  labels:
    app.kubernetes.io/component: {{ .Release.Name }}
    app.kubernetes.io/name: {{ .Release.Name }}
type: Opaque
data:
  password: {{ .Values.postgresql.db.password | b64enc | quote }}
---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-serviceaccount
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/component: postgresql-server