apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-nginx-secret
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/component: nginx-server
data:
  https1.cert: {{ .Values.cert.base64EncodedCrt }}
  https1.key: {{ .Values.cert.base64EncodedKey }}
