apiVersion: v1
Version: 1.0
name: Custom Governance
description: Custom Governance GKE deployer.
keywords:
- governance
- security
- audit
maintainers:
- email: hassaan@google.com
  name: Custom Governance
name: custom-governance
