x-google-marketplace:
  schemaVersion: v2

  applicationApiVersion: v1beta1

  publishedVersion: "$TAG"
  publishedVersionMetadata:
    releaseNote: >-
      A regular update.
    releaseTypes:
      - Feature
    recommended: false

  images:
    '':
      properties:
        elasticsearch.image.repo:
          type: REPO_WITH_REGISTRY
        elasticsearch.image.tag:
          type: TAG
    kibana:
      properties:
        kibana.image:
          type: FULL
    fluentd:
      properties:
        fluentd.image:
          type: FULL
    ubuntu16_04:
      properties:
        initImage:
          type: FULL
    prometheus-to-sd:
      properties:
        metrics.image:
          type: FULL

properties:
  name:
    type: string
    x-google-marketplace:
      type: NAME
  namespace:
    type: string
    x-google-marketplace:
      type: NAMESPACE
  elasticsearch.replicas:
    type: integer
    title: Elasticsearch replicas
    description: The number of replicas for Elasticsearch StatefulSet
    default: 2
    minimum: 2
  elasticsearch.persistence.storageClass:
    type: string
    title: StorageClass
    description: You can choose an existing StorageClass or create a new one.
    x-google-marketplace:
      type: STORAGE_CLASS
      storageClass:
        type: SSD
  elasticsearch.persistence.size:
    type: string
    title: Storage size for persistent volumes
    default: "20Gi"
    description: Elasticsearch storage size
    pattern: '^[1-9][0-9]*(\.[0-9]+)?[TGM]i?$'

  fluentd.serviceAccount:
    type: string
    title: Fluentd Service Account
    description: Service account to assign to Fluentd StatefulSet
    x-google-marketplace:
      type: SERVICE_ACCOUNT
      serviceAccount:
        roles:
        - type: ClusterRole
          rulesType: CUSTOM
          rules:
          - apiGroups: [""]
            resources: ["pods", "namespaces"]
            verbs: ["get", "list", "watch"]
  metrics.exporter.enabled:
    type: boolean
    title: Enable Stackdriver Metrics Exporter
    description: Your GCP project should have Stackdriver enabled. For non-GCP clusters,
      export of metrics to Stackdriver is not supported yet
    default: false

required:
- name
- namespace
- elasticsearch.replicas
- fluentd.serviceAccount
- metrics.exporter.enabled
