x-google-marketplace:
  schemaVersion: v2

  applicationApiVersion: v1beta1

  publishedVersion: "$TAG"
  publishedVersionMetadata:
    releaseNote: >-
      A regular update.
    releaseTypes:
      - Feature
    recommended: false

  images:
    '':
      properties:
        orientdb.image.repo:
          type: REPO_WITH_REGISTRY
        orientdb.image.tag:
          type: TAG

  clusterConstraints:
    resources:
    - replicas: 3
      requests:
        cpu: 1000m
        memory: 2Gi
      affinity:
        simpleNodeAffinity:
          type: REQUIRE_ONE_NODE_PER_REPLICA
          minimumNodeCount: 3

properties:
  name:
    type: string
    x-google-marketplace:
      type: NAME
  namespace:
    type: string
    x-google-marketplace:
      type: NAMESPACE
  deployer.image:
    type: string
    x-google-marketplace:
      type: DEPLOYER_IMAGE
  orientdb.persistence.storageClass:
    type: string
    title: StorageClass
    description: You can choose an existing StorageClass or create new one.
    x-google-marketplace:
      type: STORAGE_CLASS
      storageClass:
        type: SSD
  orientdb.persistence.storage.size:
    type: string
    title: Storage size for main storage of OrientDB server
    default: "10Gi"
    description: OrientDB main storage size
    pattern: '^[1-9][0-9]*(\.[0-9]+)?[TGM]i?$'
  orientdb.persistence.backup.size:
    type: string
    title: Storage size for backup storage of OrientDB server
    default: "2Gi"
    description: OrientDB backup storage size
    pattern: '^[1-9][0-9]*(\.[0-9]+)?[TGM]i?$'
  orientdb.replicas:
    type: integer
    title: Replicas
    description: The number of Pod replicas
    default: 3
  orientdb.rootPassword:
    type: string
    x-google-marketplace:
      type: GENERATED_PASSWORD
      generatedPassword:
        length: 10
        includeSymbols: False
        base64: False

required:
- name
- namespace
- orientdb.persistence.storage.size
- orientdb.persistence.backup.size
- orientdb.rootPassword
