apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: "{{ .Release.Name }}"
  namespace: "{{ .Release.Namespace }}"
  labels:
    app.kubernetes.io/name: "{{ .Release.Name }}"
  annotations:
    kubernetes-engine.cloud.google.com/icon: >-
      data:image/png;base64,{{ .Files.Get "logo.png" | b64enc }}
    marketplace.cloud.google.com/deploy-info: '{"partner_id": "click-to-deploy-containers", "product_id": "aditum", "partner_name": "Click To Deploy"}'
spec:
  descriptor:
    type: Custom Governance
    version: "{{ .Values.cg.image.tag }}"
  info:
    - name: Custom Governance site URL
      value: "https://{{ .Values.certificate.hostname }}"
  selector:
    matchLabels:
      app.kubernetes.io/name: "{{ .Release.Name }}"
  componentKinds:
  - group: cloud.google.com
    kind: BackendConfig
  - group: extensions
    kind: Ingress
  - group: networking.gke.io
    kind: ManagedCertificate
  - group: ''
    kind: Secret
  - group: extensions
    kind: Deployment
  - group: ''
    kind: Service
