# Daily backend data update job
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: cron-create-report
  namespace: "{{ .Release.Namespace }}"
spec:
  schedule: "0 0 * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: reports
            image: gcr.io/abc-aditum-producer-prod/buildpack-deps:curl
            args:
            - /bin/sh
            - -ec
            - curl -v -H "x-goog-cg-cron:true" cg-service:80/caiReports/create
          restartPolicy: Never
