apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-jenkins
  labels: &JenkinsLabels
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/component: jenkins-master
spec:
  replicas: 1
  selector:
    matchLabels: *JenkinsLabels
  serviceName: {{ .Release.Name }}-jenkins-ui
  template:
    metadata:
      labels: *JenkinsLabels
    spec:
      initContainers:
        - name: volume-permissions-fix
          image: "{{ .Values.jenkins.image.repo }}:{{ .Values.jenkins.image.tag }}"
          command: ["sh", "-c", "chown 1000:1000 /var/jenkins_home"]
          securityContext:
            runAsUser: 0
          volumeMounts:
          - name: {{ .Release.Name }}-jenkins-pvc
            mountPath: /var/jenkins_home
      containers:
      - name: jenkins-master
        image: "{{ .Values.jenkins.image.repo }}:{{ .Values.jenkins.image.tag }}"
        ports:
        - containerPort: 8080
        - containerPort: 50000
        volumeMounts:
        - name: {{ .Release.Name }}-jenkins-pvc
          mountPath: /var/jenkins_home
        readinessProbe:
          httpGet:
            path: /login
            port: 8080
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 2
          failureThreshold: 5
        env:
        - name: JENKINS_OPTS
          value: ''
        - name: JAVA_OPTS
          value: '-Xmx1800m'
        - name: INSTALL_MONITORING
          value: 'true'
        resources:
          limits:
            memory: 2.0Gi
          requests:
            cpu: 100m
            memory: 2.0Gi
  volumeClaimTemplates:
  - metadata:
      name: {{ .Release.Name }}-jenkins-pvc
      labels: *JenkinsLabels
    spec:
      accessModes:
      - ReadWriteOnce
      storageClassName: {{ .Values.jenkins.persistence.storageClass }}
      resources:
        requests:
          storage: {{ .Values.jenkins.persistence.size }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-jenkins-ui
  labels: &JenkinsLabels
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/component: jenkins-master
spec:
  type: NodePort
  selector: *JenkinsLabels
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      name: ui
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-jenkins-agents-connector
  labels: &JenkinsLabels
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/component: jenkins-master
spec:
  selector: *JenkinsLabels
  ports:
    - protocol: TCP
      port: 50000
      targetPort: 50000
      name: agents-connector
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-tls
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/component: jenkins-master
data:
  tls.key: |
{{ .Values.tls.base64EncodedPrivateKey | indent 4 }}
  tls.crt: |
{{ .Values.tls.base64EncodedCertificate | indent 4 }}
type: kubernetes.io/tls
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-jenkins-ui
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/component: jenkins-master
spec:
  tls:
  - secretName: {{ .Release.Name }}-tls
  backend:
    serviceName: {{ .Release.Name }}-jenkins-ui
    servicePort: 8080
