apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: "{{ .Release.Name }}"
  annotations:
    kubernetes-engine.cloud.google.com/icon: >-
      data:image/png;base64,{{ .Files.Get "logo.png" | b64enc }}
    marketplace.cloud.google.com/deploy-info: '{"partner_id": "click-to-deploy-containers", "product_id": "etcd", "partner_name": "Google Click to Deploy"}'
  labels:
    app.kubernetes.io/name: "{{ .Release.Name }}"
spec:
  descriptor:
    type: etcd
    version: "{{ .Values.image.tag }}"
    description: |-
      etcd is a distributed key-value store, designed for distributed systems.
      It offers a gRPC API, automatic TLS encryption, and optional client certificate authentication.

      # Support
      Google does not offer support for this solution. However, community support is available on
      [Stack Overflow](https://stackoverflow.com/questions/tagged/etcd/).
      Additional community support is available on the [etcd website](http://etcd.io).
    maintainers:
    - name: Google Click to Deploy
      url: https://cloud.google.com/solutions/#click-to-deploy
    links:
    - description: 'User Guide: Google Click to Deploy etcd'
      url: https://github.com/GoogleCloudPlatform/click-to-deploy/blob/master/k8s/etcd/README.md
    - description: 'Official documentation for etcd'
      url: https://github.com/etcd-io/etcd/tree/master/Documentation
    notes: |-
      # Get the authentication credentials for the cluster

      ```shell
      gcloud container clusters get-credentials [CLUSTER_NAME] --zone [CLUSTER_ZONE]
      ```

      where:
      * `[CLUSTER_NAME]` is the name of the cluster for this application
      * `[CLUSTER_ZONE]` is the zone in which the cluster is running

      For information on getting the credentials for a cluster, read the [Google Kubernetes Engine documentation](https://cloud.google.com/kubernetes-engine/docs/quickstart#get_authentication_credentials_for_the_cluster).

      Make sure that all components are in `ready` status.
      To connect to the etcd service from your machine, install the latest release of the etcd binaries. For more information about installing the etcd binaries, visit the [official etcd documentation](https://github.com/etcd-io/etcd/releases).

      Forward the etcd service client port to your machine:
      ```shell
      kubectl port-forward svc/{{ .Release.Name }}-etcd --namespace {{ .Release.Namespace }} 2379
      ```

      Then run the below commands in a new terminal window:
      ```shell
      # Get etcd root user password
      ETCD_ROOT_PASSWORD=$(kubectl get secret --namespace {{ .Release.Namespace }} {{ .Release.Name }}-etcd -o jsonpath="{.data.etcd-root-password}" | base64 --decode)

      # Interact with etcd
      export ETCDCTL_API=3

      ## Put sample value using credentials
      etcdctl --user root:${ETCD_ROOT_PASSWORD} --endpoints=http://localhost:2379 put foo bar

      ## Get value
      etcdctl --user root:${ETCD_ROOT_PASSWORD} --endpoints=http://localhost:2379 get foo
      ```
  info:
  - name: etcd
    type: Reference
    valueFrom:
      serviceRef:
        name: "{{ .Release.Name }}-etcd"
  - name: etcd root username
    value: root
  - name: etcd root password
    type: Reference
    valueFrom:
      secretKeyRef:
        key: etcd-root-password
        name: "{{ .Release.Name }}-etcd"
  selector:
    matchLabels:
      app.kubernetes.io/name: "{{ .Release.Name }}"
  componentKinds:
  - group: v1
    kind: PersistentVolumeClaim
  - group: v1
    kind: Service
  - group: apps/v1
    kind: StatefulSet
  - group: v1
    kind: ConfigMap
  - group: v1
    kind: Secret
