application_api_version: v1beta1
properties:
  name:
    type: string
    x-google-marketplace:
      type: NAME
  namespace:
    type: string
    x-google-marketplace:
      type: namespace
  grafana.image:
    type: string
    default: $REGISTRY:$TAG
    x-google-marketplace:
      type: IMAGE
  grafana.initImage:
    type: string
    default: $REGISTRY/debian9:$TAG
    x-google-marketplace:
      type: IMAGE
  grafana.password:
    type: string
    x-google-marketplace:
      type: GENERATED_PASSWORD
      generatedPassword:
        length: 12
  grafana.serviceaccount:
    type: string
    title: Grafana Service Account
    description: Service account to assign to main Grafana StatefulSet
    x-google-marketplace:
      type: SERVICE_ACCOUNT
      serviceAccount:
        roles:
        - type: ClusterRole
          rulesType: PREDEFINED
          rulesFromRoleName: cluster-admin
required:
- name
- namespace
- grafana.image
- grafana.initImage
- grafana.password
- grafana.serviceaccount
