apiVersion: apps/v1beta2
kind: StatefulSet
metadata:
  labels: &InfluxDBDeploymentLabels
    app.kubernetes.io/name: $APP_INSTANCE_NAME
    app.kubernetes.io/component: influxdb-server
  name: $APP_INSTANCE_NAME-influxdb
spec:
  replicas: 1
  selector:
    matchLabels: *InfluxDBDeploymentLabels
  serviceName: $APP_INSTANCE_NAME-influxdb-svc
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels: *InfluxDBDeploymentLabels
    spec:
      terminationGracePeriodSeconds: 180
      containers:
      - name: influxdb
        image: $IMAGE_INFLUXDB
        imagePullPolicy: Always
        args: ["influxd"]
        env:
        - name: INFLUXDB_ADMIN_ENABLED
          value: 'true'
        - name: INFLUXDB_ADMIN_USER
          valueFrom:
            secretKeyRef:
              name: $APP_INSTANCE_NAME-influxdb-secret
              key: influxdb-admin
        - name: INFLUXDB_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: $APP_INSTANCE_NAME-influxdb-secret
              key: influxdb-pass
        ports:
        - name: influxdb
          containerPort: 8086
          protocol: TCP
        - name: influx-admin
          containerPort: 8088
          protocol: TCP
        - name: influx-graphite
          containerPort: 2003
          protocol: TCP
        livenessProbe:
          tcpSocket:
            port: influxdb
          initialDelaySeconds: 10
          timeoutSeconds: 5
        readinessProbe:
          tcpSocket:
            port: influxdb
          initialDelaySeconds: 5
          timeoutSeconds: 2
        volumeMounts:
         - name: influxdb-data
           mountPath: /var/lib/influxdb
  volumeClaimTemplates:
  - metadata:
      name: $APP_INSTANCE_NAME-data-pvc
    spec:
      resources:
        requests:
          storage: 1Gi
      accessModes:
      - ReadWriteOnce
      storageClassName: standard
---
apiVersion: v1
kind: Service
metadata:
  name: $APP_INSTANCE_NAME-influxdb-svc
  labels:
    app.kubernetes.io/name: $APP_INSTANCE_NAME
    app.kubernetes.io/component: influxdb-server
spec:
  ports:
  - name: influxdb
    port: 8086
    protocol: TCP
  selector:
    app.kubernetes.io/name: $APP_INSTANCE_NAME
    app.kubernetes.io/component: influxdb-server
  type: ClusterIP # LoadBalancer
