{{- if .Values.hydra.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ .Release.Name }}
  labels:
    {{- include "hydra.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Release.Name }}
  minReplicas: {{ .Values.hydra.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.hydra.autoscaling.maxReplicas }}
{{- end }}
