---
apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: "{{ .Release.Name }}"
  namespace: "{{ .Release.Namespace }}"
  annotations:
    kubernetes-engine.cloud.google.com/icon: >-
      data:image/png;base64,{{ .Files.Get "logo.png" | b64enc }}
    marketplace.cloud.google.com/deploy-info: '{"partner_id": "click-to-deploy-containers", "product_id": "elastic-gke-logging", "partner_name": "Google Click to Deploy"}'
  labels:
    app.kubernetes.io/name: "{{ .Release.Name }}"
spec:
  descriptor:
    type: Elastic GKE Logging
    version: "{{ .Values.elasticsearch.image.tag }}"
    description: |-
      Elastic GKE Logging is an application that provides a fully functional solution for collecting
      and analyzing logs from a Kubernetes cluster. It is built on top of popular open-source systems,
      including Fluentd for logs collection and Elasticsearch with Kibana for searching and analyzing
      data.

      # Support
      Google does not offer support for this solution. However, community support is available on
      Stack Overflow for [Fluentd](https://stackoverflow.com/questions/tagged/fluentd/),
      [Elasticsearch](https://stackoverflow.com/questions/tagged/elasticsearch/) and
      [Kibana](https://stackoverflow.com/questions/tagged/kibana/).
    maintainers:
    - name: Google Click to Deploy
      url: https://cloud.google.com/solutions/#click-to-deploy
    links:
    - description: 'User Guide: Google Click to Deploy Elastic GKE Logging'
      url: https://github.com/GoogleCloudPlatform/click-to-deploy/tree/master/k8s/elastic-gke-logging/README.md
    - description: 'Elasticsearch: Getting Started'
      url: https://www.elastic.co/webinars/getting-started-elasticsearch
    - description: 'Kibana official documentation'
      url: https://www.elastic.co/guide/en/kibana/6.x/index.html
    - description: 'Fluentd Quickstart Guide'
      url: https://docs.fluentd.org/v1.0/articles/quickstart
    notes: |-
      # Access Kibana UI

      By default, the Kibana Service does not have an external IP. To open Kibana UI you can
      use `kubectl port-forward` and access the UI from your local machine.

      Run the following command in background:

      ```
      kubectl port-forward -n {{ .Release.Namespace }} \
        svc/{{ .Release.Name }}-kibana-svc 5601
      ```

      Open Kibana in your web browser with `http://localhost:5601/`.

      # Discover the logs

      ## Index Pattern

      Your installation automatically adds a default Index Pattern to be tracked by Kibana - it
      matches the Fluentd DaemonSet configuration and equals to `logstash-*`. Thanks to this
      configuration you can view the logs from the Kubernetes cluster immediately after the
      successful installation.

      ## Saved searches

      Kibana allows to save predefined searches with their filters and presented columns
      configuration. To view the searches shipped with this installation, visit the `Discover` page
      of Kibana and in the top menu, click on the `Open` option. It will present a list of some useful
      searches, including logs from: GKE Apps, kubelet, docker, kernel and others.
  info:
  - name: Forward Kibana port locally
    value: kubectl port-forward svc/{{ .Release.Name }}-kibana-svc -n {{ .Release.Namespace }} 5601
  - name: Kibana UI URL
    value: http://localhost:5601/
  selector:
    matchLabels:
      app.kubernetes.io/name: "{{ .Release.Name }}"
  componentKinds:
  - group: v1
    kind: ConfigMap
  - group: apps/v1
    kind: Deployment
  - group: apps/v1
    kind: DaemonSet
  - group: batch/v1
    kind: Job
  - group: v1
    kind: PersistentVolumeClaim
  - group: v1
    kind: Service
  - group: apps/v1
    kind: StatefulSet
