properties:
  APP_INSTANCE_NAME:
    type: string
    x-google-marketplace:
      type: NAME
  NAMESPACE:
    type: string
    x-google-marketplace:
      type: NAMESPACE
  SERVICE_ACCOUNT:
    type: string
    title: Cluster Admin Service Account
    description: >-
      Name of a service account in the target namespace that
      has cluster-admin permissions. This is needed for the operator
      to create Spark CRD and jobs.
    x-google-marketplace:
      type: SERVICE_ACCOUNT
      serviceAccount:
        roles:
        - type: ClusterRole
          rulesType: PREDEFINED
          # TODO(liyinan926): Reduce the permission set.
          rulesFromRoleName: cluster-admin
required:
- APP_INSTANCE_NAME
- NAMESPACE
- SERVICE_ACCOUNT
x-google-marketplace:
  images:
    ? ''
    : properties:
        SPARK_OPERATOR_IMAGE:
          type: FULL
  applicationApiVersion: v1beta1
  schemaVersion: v2
  managedUpdates:
    kalmSupported: true
  publishedVersion: $TAG
  publishedVersionMetadata:
    recommended: false
    releaseNote: A regular update.
    releaseTypes:
    - Feature
