properties:
  APP_INSTANCE_NAME:
    type: string
    x-google-marketplace:
      type: NAME
  NAMESPACE:
    type: string
    x-google-marketplace:
      type: NAMESPACE
  IMAGE_INFLUXDB:
    type: string
    default: $REGISTRY:$TAG
    x-google-marketplace:
      type: IMAGE
  INFLUXDB_ADMIN_USER:
    type: string
    default: influxdb-admin
    x-google-marketplace:
      type: string
  INFLUXDB_ADMIN_PASSWORD:
    type: string
    x-google-marketplace:
      type: GENERATED_PASSWORD
      generatedPassword:
        length: 32
required:
- APP_INSTANCE_NAME
- NAMESPACE
- IMAGE_INFLUXDB
- INFLUXDB_ADMIN_USER
- INFLUXDB_ADMIN_PASSWORD
