---
apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: "{{ .Release.Name }}"
  namespace: "{{ .Release.Namespace }}"
  annotations:
    kubernetes-engine.cloud.google.com/icon: >-
      data:image/png;base64,{{ .Files.Get "logo.png" | b64enc }}
    marketplace.cloud.google.com/deploy-info: '{"partner_id": "click-to-deploy-containers", "product_id": "elasticsearch", "partner_name": "Google Click to Deploy"}'
  labels:
    app.kubernetes.io/name: "{{ .Release.Name }}"
spec:
  descriptor:
    type: Elasticsearch
    version: "{{ .Values.elasticsearch.image.tag }}"
    description: |-
      Elasticsearch is an open-source search engine that provides a distributed, multitenant-capable
      full-text search engine with an HTTP web interface and schema-free JSON documents.

      # Support
      Google does not offer support for this solution. However, community support is available on
      [Stack Overflow](https://stackoverflow.com/questions/tagged/elasticsearch/).
      Additional community support is available on [elastic.co forums](https://discuss.elastic.co/).
    maintainers:
    - name: Google Click to Deploy
      url: https://cloud.google.com/solutions/#click-to-deploy
    links:
    - description: 'User Guide: Google Click to Deploy Elasticsearch'
      url: https://github.com/GoogleCloudPlatform/click-to-deploy/blob/master/k8s/elasticsearch/README.md
    - description: 'Elasticsearch: Getting Started'
      url: https://www.elastic.co/webinars/getting-started-elasticsearch
    notes: |-
      # Expose Elasticsearch service

      By default, the service does not have an external IP. Run the
      following command to expose an external IP:

      ```
      kubectl patch service/"{{ .Release.Name }}-elasticsearch-svc" \
        --namespace "{{ .Release.Namespace }}" \
        --patch '{"spec": {"type": "LoadBalancer"}}'
      ```

        # Access Elasticsearch

        Get the external IP of the Elasticsearch service:

      ```
      SERVICE_IP=$(kubectl get service/{{ .Release.Name }}-elasticsearch-svc \
        --namespace {{ .Release.Namespace }} \
        --output jsonpath='{.status.loadBalancer.ingress[0].ip}')

      echo "http://${SERVICE_IP}:9200"
      ```

      Note that it might take some time for the external IP to be provisioned.

      # Scale the cluster

      To scale the cluster, use either a GKE UI (use the Scale option in the
      StatefulSet details screen) or the following command:

      ```
      kubectl scale statefulsets "{{ .Release.Name }}-elasticsearch" \
        --namespace "{{ .Release.Namespace }}" --replicas=<new-replicas>
      ```

      By default, there are 2 replicas to satisfy the minimum master quorum.
      To increase resilience, it is recommended to scale the number of replicas
      to at least 3.

      For more information about the StatefulSets scaling, check the
      [Kubernetes documentation](https://kubernetes.io/docs/tasks/run-application/scale-stateful-set/#kubectl-scale).
  selector:
    matchLabels:
      app.kubernetes.io/name: "{{ .Release.Name }}"
  componentKinds:
  - group: v1
    kind: ConfigMap
  - group: v1
    kind: PersistentVolumeClaim
  - group: v1
    kind: Service
  - group: apps/v1
    kind: StatefulSet
