# Copyright 2022 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


cloudbuild:
  enable_parallel: true
versions:
- dir: 5/debian11/5.1.0
  from: marketplace.gcr.io/google/debian11
  packages:
    dockerneo4j:
      sha256: 5ec1db0bf99918247d18dcb8b0f019a3f959a0fc57ce612738272c5a26f4576f
      version: 5.1.0
    neo4j:
      sha256: c8086d1f8558376754e7248a7d12838f024ca2699aa59e0aba30816b229ed4f4
      version: 5.1.0
    tini:
      sha256: 93dcc18adc78c65a028a84799ecf8ad40c936fdfc5f2a57b1acda5a8117fa82c
      version: 0.19.0
  repo: neo4j5
  tags:
  - 5.1.0-debian11
  - 5.1-debian11
  - 5-debian11
  - 5.1.0
  - '5.1'
  - '5'
  - latest

