nginx:
  image:
    repo: null
    tag: null
  initImage: null
  replicas: null
  persistence:
    storageClass: null
    size: 1Gi
tls:
  base64EncodedPrivateKey: null
  base64EncodedCertificate: null
exporter:
  image: null
metrics:
  image: null
  curatedExporter:
    enabled: true
  exporter:
    enabled: false
publicIp:
  available: true
