# Copyright 2024 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


cloudbuild:
  enable_parallel: false
  machineType: E2_HIGHCPU_32
versions:
- dir: 6/debian11/6.6
  from: marketplace.gcr.io/google/c2d-debian11
  packages:
    golang:
      version: '1.20'
    pd:
      version: 6.6.0
    tikv:
      version: 6.6.0
  repo: tikv6
  tags:
  - 6.6.0-debian11
  - 6.6-debian11
  - 6-debian11
  - 6.6.0
  - '6.6'
  - '6'
  - latest
- dir: 6/debian11/6.5
  from: marketplace.gcr.io/google/c2d-debian11
  packages:
    golang:
      version: '1.20'
    pd:
      version: 6.5.1
    tikv:
      version: 6.5.1
  repo: tikv6
  tags:
  - 6.5.1-debian11
  - 6.5-debian11
  - 6.5.1
  - '6.5'

