# Copyright 2023 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


cloudbuild:
  enable_parallel: false
versions:
- dir: 2/debian11/2.4
  from: marketplace.gcr.io/google/c2d-debian11
  packages:
    storm:
      version: 2.4.0
  repo: storm2
  tags:
  - 2.4.0-debian11
  - 2.4-debian11
  - 2-debian11
  - 2.4.0
  - '2.4'
  - '2'
  - latest

