name: ci-tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # Upgraded to v4
    - uses: actions/checkout@v4

    # Upgraded to v5
    - uses: actions/setup-python@v5
      with:
        python-version: '3.x'
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip jinja2 pyyaml

    # Use the Action instead of the broken wget link
    - name: Setup Chef
      uses: chef/setup-chef@v1
      with:
        chef_version: latest
        accept_chef_license: true

    - name: Run tests
      run: make python-test vm-lint vm-generate-triggers
